/* Generate the static newsroom and English briefs from reviewed source content. */
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const content = JSON.parse(fs.readFileSync(path.join(root, 'content/robotics-news.json'), 'utf8'));
const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const validDate = value => /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(value)) && new Date(value).toISOString().slice(0,10) === value;
const date = (value, style='short') => new Intl.DateTimeFormat('en-GB', {day:'numeric',month:style,year:'numeric',timeZone:'UTC'}).format(new Date(value+'T12:00:00Z'));
if(!validDate(content.editionDate)) throw new Error('Invalid edition date');
const ids = new Set();
for(const story of content.stories) {
    if(!/^[a-z0-9-]+$/.test(story.id) || ids.has(story.id)) throw new Error('Invalid or duplicate story ID');
    ids.add(story.id);
    if(!validDate(story.date) || !validDate(story.source.published) || story.date > content.editionDate) throw new Error('Invalid story date');
    if(!['Humanoids','Embodied AI','Real-world robots','Industry'].includes(story.category)) throw new Error('Unknown category');
    if(!story.title || !story.summary || !Array.isArray(story.paragraphs) || !story.paragraphs.length) throw new Error('Missing story content');
    const image = story.image;
    if(!image || !/^assets\/news\/[a-z0-9-]+\.webp$/.test(image.src) || !fs.existsSync(path.join(root,image.src)) || !image.alt || !image.caption || !image.credit || !['cover','contain'].includes(image.fit) || !Number.isInteger(image.width) || image.width<=0 || !Number.isInteger(image.height) || image.height<=0) throw new Error(`Missing or invalid story image: ${story.id}`);
    for(const url of [image.creditUrl,image.sourceUrl]) if(new URL(url).protocol!=='https:') throw new Error('Image sources must use HTTPS');
    for(const source of [story.source,story.additionalSource].filter(Boolean)) if(new URL(source.url).protocol !== 'https:') throw new Error('Sources must use HTTPS');
}
const stories = [...content.stories].sort((a,b)=>b.date.localeCompare(a.date));
const featured = stories.find(story=>story.id===content.featuredId);
if(!featured) throw new Error('Featured story not found');
const storyPath = story => `news/${story.id}.html`;
const kicker = story => `<div class="story-kicker"><span>${escape(story.category)}</span><span class="place">/ ${escape(story.location)}</span></div>`;
const meta = story => `<div class="story-meta"><span>${escape(story.source.name)}</span><span class="meta-separator" aria-hidden="true">·</span><time datetime="${story.date}">${date(story.date)}</time></div>`;
const header = require('./site-header.cjs');
const imageTag = (story,prefix='',priority=false) => `<img src="${prefix}${escape(story.image.src)}" alt="${escape(story.image.alt)}" width="${story.image.width}" height="${story.image.height}" class="image-${story.image.fit}" ${priority?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const imageCredit = story => `<a href="${escape(story.image.creditUrl)}" target="_blank" rel="noopener noreferrer">Image: ${escape(story.image.credit)} ↗</a>`;
const picture = (story,prefix='',priority=false) => `<figure class="story-picture">${imageTag(story,prefix,priority)}<figcaption><span>${escape(story.image.caption)}</span>${imageCredit(story)}</figcaption></figure>`;
function footer(prefix='') { return `<footer><div class="news-shell footer-inner"><span>© ${content.editionDate.slice(0,4)} SuperRobots · Stay curious. Build something.</span><nav aria-label="Footer navigation"><a href="${prefix}index.html#about">About this edition</a><a href="${prefix}news-feed.xml">Robotics RSS</a><a href="${prefix}learn.html">Learning hub</a><a href="https://github.com/superrobots/superrobots.github.io" target="_blank" rel="noopener noreferrer">GitHub ↗</a></nav></div></footer>`; }
const featuredMarkup = `<article class="lead-story"><a class="lead-visual" href="${storyPath(featured)}" aria-label="Read: ${escape(featured.title)}"><img src="assets/robotics-editorial.svg" alt="Original illustration of a humanoid robot in an architectural setting" width="900" height="520" fetchpriority="high"><span class="image-label">Editorial illustration</span></a>${kicker(featured)}<h2 class="lead-title"><a href="${storyPath(featured)}">${escape(featured.title)}</a></h2><p>${escape(featured.summary)}</p>${meta(featured)}</article>`;
const briefing = stories.filter(story=>story.id!==featured.id).slice(0,3).map((story,index)=>`<article class="briefing-item"><span class="briefing-number" aria-hidden="true">0${index+1}</span><div>${kicker(story)}<h3><a href="${storyPath(story)}">${escape(story.title)}</a></h3>${meta(story)}</div></article>`).join('\n');
const cards = stories.map(story=>`<article class="news-card" data-category="${escape(story.category)}" data-search="${escape([story.title,story.summary,story.source.name,story.location,story.category].join(' ').toLowerCase())}">${kicker(story)}<h3><a href="${storyPath(story)}">${escape(story.title)}</a></h3><p>${escape(story.summary)}</p>${meta(story)}<a class="card-link" href="${storyPath(story)}" aria-label="Read English brief: ${escape(story.title)}"><span>Read English brief</span><span aria-hidden="true">↗</span></a></article>`).join('\n');
const structured = {'@context':'https://schema.org','@type':'CollectionPage',name:'SuperRobots — Robotics News from China, in English',url:'https://superrobots.org/',inLanguage:'en',dateModified:content.editionDate,mainEntity:{'@type':'ItemList',itemListElement:stories.map((story,index)=>({'@type':'ListItem',position:index+1,url:`https://superrobots.org/${storyPath(story)}`,name:story.title}))}};
const replacements = {header:header(),footer:footer(),editionDate:content.editionDate,editionDisplay:date(content.editionDate).toUpperCase(),editionLong:date(content.editionDate,'long'),featuredStory:featuredMarkup,briefingStories:briefing,newsCards:cards,storyCount:stories.length,structuredData:JSON.stringify(structured).replace(/</g,'\\u003c')};
let template = fs.readFileSync(path.join(__dirname,'news-home.template.html'),'utf8');
template = template.replace(/\{\{(\w+)\}\}/g,(_,key)=>{if(!(key in replacements))throw new Error(`Unknown placeholder ${key}`);return replacements[key];});
fs.writeFileSync(path.join(root,'index.html'),template);
fs.mkdirSync(path.join(root,'news'),{recursive:true});
for(const story of stories) {
    const schema = {'image':`https://superrobots.org/${story.image.src}`,'@context':'https://schema.org','@type':'Article',headline:story.title,description:story.summary,datePublished:content.editionDate,dateModified:content.editionDate,inLanguage:'en',author:{'@type':'Organization',name:'SuperRobots'},publisher:{'@type':'Organization',name:'SuperRobots'},citation:[story.source.url,...(story.additionalSource?[story.additionalSource.url]:[])],mainEntityOfPage:`https://superrobots.org/${storyPath(story)}`};
    fs.writeFileSync(path.join(root,storyPath(story)),`<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${escape(story.title)} | SuperRobots</title><meta name="description" content="${escape(story.summary)}"><link rel="canonical" href="https://superrobots.org/${storyPath(story)}"><link rel="icon" href="../images/favicon.png"><link rel="stylesheet" href="../news.css"><meta property="og:type" content="article"><meta property="og:title" content="${escape(story.title)}"><meta property="og:description" content="${escape(story.summary)}"><meta property="og:url" content="https://superrobots.org/${storyPath(story)}"><meta property="og:image" content="https://superrobots.org/${escape(story.image.src)}"><meta property="og:image:alt" content="${escape(story.image.alt)}"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head>
<body class="news-site"><a class="skip-link" href="#main">Skip to content</a>${header('../')}<main class="news-shell" id="main"><article class="article-shell"><a class="back-to-news" href="../index.html#latest">← Back to all stories</a>${kicker(story)}<h1>${escape(story.title)}</h1><p class="article-deck">${escape(story.summary)}</p><div class="story-meta"><span>${escape(story.dateLabel)} <time datetime="${story.date}">${date(story.date)}</time></span><span class="meta-separator" aria-hidden="true">·</span><span>${escape(story.source.type)}</span><span class="meta-separator" aria-hidden="true">·</span><span>English brief</span></div>${picture(story,'../',true)}<div class="article-body">${story.paragraphs.map(p=>`<p>${escape(p)}</p>`).join('\n')}</div><section class="article-sources" aria-label="Original sources"><h2>Read the original source</h2><a href="${escape(story.source.url)}" target="_blank" rel="noopener noreferrer">${escape(story.source.name)} · Chinese original ↗</a>${story.additionalSource?`<br><a href="${escape(story.additionalSource.url)}" target="_blank" rel="noopener noreferrer">${escape(story.additionalSource.name)} · Chinese original ↗</a>`:''}<p>Source published ${date(story.source.published)}. Translated and summarized by SuperRobots on ${date(content.editionDate)}. This brief is an English editorial summary, not a full translation. Company statements remain attributed to the company.</p></section></article></main>${footer('../')}</body></html>`);
}
const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>SuperRobots — China Robotics News</title><link>https://superrobots.org/</link><description>English summaries of Chinese robotics news and primary sources.</description><language>en</language><lastBuildDate>${new Date(content.editionDate+'T12:00:00+08:00').toUTCString()}</lastBuildDate><atom:link href="https://superrobots.org/news-feed.xml" rel="self" type="application/rss+xml"/>${stories.map(story=>`<item><title>${escape(story.title)}</title><link>https://superrobots.org/${storyPath(story)}</link><guid isPermaLink="true">https://superrobots.org/${storyPath(story)}</guid><description>${escape(story.summary+' Original source: '+story.source.name+' ('+story.source.url+').')}</description><pubDate>${new Date(content.editionDate+'T12:00:00+08:00').toUTCString()}</pubDate><category>${escape(story.category)}</category></item>`).join('\n')}</channel></rss>`;
fs.writeFileSync(path.join(root,'news-feed.xml'),rss);
let sitemap = fs.readFileSync(path.join(root,'sitemap.xml'),'utf8');
sitemap = sitemap.replace(/\s*<url>\s*<loc>https:\/\/superrobots\.org\/(?:news\/[^<]+|learn\.html)<\/loc>[\s\S]*?<\/url>/g,'');
const sitemapEntries = ['learn.html',...stories.map(storyPath)].map(file=>`    <url><loc>https://superrobots.org/${file}</loc><lastmod>${content.editionDate}</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>`).join('\n');
sitemap = sitemap.replace('</urlset>',sitemapEntries+'\n</urlset>');
fs.writeFileSync(path.join(root,'sitemap.xml'),sitemap);
console.log(`Built newsroom, ${stories.length} English briefs, RSS, and sitemap for ${content.editionDate}.`);
